server:
  port: 9090

spring:
  application:
    name: msvc-course

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/courseDb
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5 # Intervalo de renovación
    lease-expiration-duration-in-seconds: 10 # Duración antes de expirar
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka